### ISSUE TITLE
RAM drive: why not auto-mount the new device?

### ISSUE THREAD

**Issue by Kriechi** [facetheheat/Alfred#1]
Why do you not mount the newly created RAM drive directly?
RAMDiskCreator does this - and it works perfectly.

Use this command:

``` sh
diskutil erasevolume HFS+ 'RAM-Disk' `hdiutil attach -nomount ram://1048576`
```

**Comment by facetheheat** [comment]
Because I use different types of file system, line ExtFS, NTFS, HFS.

**Comment by Kriechi** [comment]
Interesting idea, fair enough.

Just my 2 cents:
Not sure how much time you want to spend on development for this workflow:
but it would be nice to add at least the mounting with a _default_ filesystem...
maybe the FS choice could be a second argument like: `ram 2g ntfs` (but it would default to HFS+)

**Comment by facetheheat** [comment]
Hi, Thomas.
Check a new version, please.

**Comment by Kriechi** [comment]
Yeah! Real nice!
